import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Capstone Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
